### ISSUE TITLE
Volume dashboard / QOS graphs show no data.

### ISSUE THREAD

**Issue by slater0013** [NetApp/harvest#1308]
**Describe the bug**
Hello,
In the cDOT/ONTAP:Volume dashboard, when selecting a Datacenter, a Cluster, a SVM, and wether you select or not a volume, the rows "Top Volume End-to-End QoS Drilldown" and "Top Volume QoS Resource Latency Drilldown" only show "No data" pannels.

**Environment**

- Harvest version: harvest version 22.08.0-1 (commit 93db10a) (build date 2022-08-19T09:08:45-0400) linux/amd64
- OS: Debian 11.4 
- Install method: debian package
- ONTAP Version: 9.8P11

**Actual behavior**
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/49311455/191986205-32adb025-dc42-46eb-8676-af196a22127a.png">

Thanks ;)
GS

**Comment by cgrinds** [comment]
hi @slater0013 can you double check that you enabled the QOS counters [here](https://github.com/NetApp/harvest/blob/034deba4ab4bcbf39c5a0e10c3180a229bf6216b/conf/zapiperf/default.yaml#L56)?

**Comment by slater0013** [comment]
Hello,
You are right, QOS Counters were commented.

But...

To see the QOS Datas, I need to unselect the volume in dashboard filters. Even when I have more than 10 volumes in the volume list for one SVM, the graph only shows 2 volume QOS datas (root volume + 1)

When I run "vol show -vserver MyVserver -fields qos-policy-group" the 2 volumes that do not have any qos policy are graphed.

Volumes associated with a QOS policy do not show up on graphs.

Thanks,
GS.

**Comment by cgrinds** [comment]
Thanks for confirming @slater0013
Thanks for the additional details, you are hitting issue #1264. Harvest was ignored user-defined workloads. This has been fixed and if you want, you can grab the latest [nightly build](https://github.com/NetApp/harvest/releases/tag/nightly).

Let us know if that works for you.

**Comment by slater0013** [comment]
Thanks !

The grafana will be used by our clients, so we'll stick to the stable branch ! Hope the next release is coming soon :D 

GS

**Comment by v3nt0** [comment]
Hi, I've un-commented the QoS counters on zapiperf/default.yaml, re-started harvest however I'm still unable to see the QoS graphs on Grafana dashboard. I see some random data, and the query type is set to 'Randon Walk' instead of the QoS queries, anyone have any clue?

**Comment by cgrinds** [comment]
hi @v3nt0 what version of Harvest are you using? We don't use random walk in our dashboards.

**Comment by v3nt0** [comment]
hi @cgrinds I'm using harvest-21.08.0-6_linux_amd64. I also found some other dashboards with random walk, really not sure what happened.
